### ISSUE TITLE
Add option to substitute original language if term is not translated

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/POEditorAPI#4]
When localization for a language is incomplete, we would want to use the source language

**Comment by matanporeh** [comment]
was this added?

**Comment by odrobnik** [comment]
Determined to be not necessary at the moment, since POEditor has a project setting to export the reference language if translations are empty

**Comment by matanporeh** [comment]
thanks

**Comment by odrobnik** [comment]
Will not do, since it is done by POEditor as discussed above.
