### ISSUE TITLE
missing documentation of how to use the cocoapod for  POEditorAPI

### ISSUE THREAD

**Issue by matanporeh** [Cocoanetics/POEditorAPI#7]
also when using this project via a pod file, the framework classes seem to be unavailable for the project using them. please describe correct installation flow

**Comment by odrobnik** [comment]
I am fixing the issue... mostly it was non-public definitions which did not expose the `POEditor` class and -functions to the importing app.

**Comment by odrobnik** [comment]
Addressed in release 1.1.0
